backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # Where uploaded images go
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "homepage"
        editor:
          preview: false
        fields:
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
          - label: "Hero Subtitle"
            name: "hero_subtitle"
            widget: "text"
Add Netlify CMS config
